export enum ActionType {
    GET_CURRENCIES = 'GET_CURRENCIES',
    GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS',
    GET_CURRENCIES_ERROR = 'GET_CURRENCIES_ERROR',
    GET_SELECT_CURRENCIES = 'GET_SELECT_CURRENCIES',
}
