export enum ActionType {
    GET_CURRENCIES = 'GET_CURRENCIES',
    GET_ALL_CURRENCIES = ' GET_ALL_CURRENCIES',
    GET_SELECT_CURRENCIES = 'GET_SELECT_CURRENCIES',
    GET_CONVERT_CURRENCIES = 'GET_CONVERT_CURRENCIES',
    GET_CURRENCIES_ERROR = 'GET_CURRENCIES_ERROR',
}
